### ISSUE TITLE
Allow filter tests based on testdox docstring

### ISSUE THREAD

**Issue by hbarcelos** [renanivo/pytest-testdox#25]
I come from the JavaScript world and most available test frameworks are based on description instead of function names. I used to "mark" some tests using a hashtag, for example: `#unit`, `#smoke`, `#regression`. That allowed me to run only some specific test cases, like:

```
mocha --grep '#unit'
```

The command above would run only the tests marked as `#unit`.

`pytest` has the `-k` flag that allows filtering tests matching its argument with the test name.
However, I can't make it work with `testdox`.

Is this possible today?

**Comment by renanivo** [comment]
Hi @hbarcelos, thank you for filling this issue.

Filter tests based on docstrings is not possible with `pytest-testdox` (it doesn't even support writing test names as docstrings, see #19), but pytest has the ability to [use _markers_ to filter tests](https://docs.pytest.org/en/latest/example/markers.html). So, instead of using `#unit` in your doctests, you could decorate the function with `@pytest.mark.unit` and run tests with `pytest -m 'unit'` or even run every test except the ones marked as "unit" with `pytest -m 'not unit'`.

I think this feature of pytest would suit your needs and it is not necessary to add something new to `pytest-testdox`.

Let me know if there's something I didn't understand in your question or any detail I missed.

**Comment by hbarcelos** [comment]
Hi @renanivo, thank you for your reply.

Yes, that makes sense.

I'll try this approach.
