### ISSUE TITLE
Replace Travis with GitHub Actions

### ISSUE THREAD

**Issue by renanivo** [renanivo/pytest-testdox#37]
Seems to be what the cool kids are doing.

**Comment by hugovk** [comment]
For the deploy part of `.travis.yml`, the [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) action can be used.

Here's an example that deploys to **TestPyPI** for merges to master, to ensure the deploy machinery works and avoid surprises on release day; and deploys to **production PyPI** for releases:

* https://github.com/hugovk/tinytext/blob/master/.github/workflows/deploy.yml

There's instructions at https://github.com/pypa/gh-action-pypi-publish, you need to put deploy tokens for TestPyPI and PyPI in `secrets.test_pypi_password` and `secrets.pypi_password` respectively.

Also, see the pro tip at https://github.com/pypa/gh-action-pypi-publish to use a SHA instead of `master`. More info: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/

Let me know if you've any questions!
